---
# tasks file for nginx
- name: Install Nginx 
  yum: 
    name: nginx
    state: latest
 
- name: Create Nginx Document Root
  file:
    path: "/var/www/html/"
    state: directory
    owner: "nginx"
    group: "nginx"
    mode: '0755'
 
- name: Set up Nginx VirtualHost
  template:
    src: wp.conf.j2
    dest: "/etc/nginx/conf.d/wp.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Set up Nginx Config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r


- name: Start nginx service
  systemd: 
    name: nginx 
    state: started 
    enabled: yes