- hosts: localhost
  gather_facts: False
  become: true
  roles:
    - nginx
    - php
    - mysql
    - wordpress
    - firewalld
  tasks:
    - name: Get the public IP 
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10

    - name: Print Info
      debug:
        msg: "Web Site : http://{{ public_ip.json.ip }}"
